Member.create(name: 'Administrator', id: 1, code: 111)
Member.create(name: '足立', id: 2, code: 222)
Member.create(name: '山下', id: 3, code: 333)
Member.create(name: '高瀬', id: 4, code: 444)
Member.create(name: '深澤', id: 5, code: 555)
Member.create(name: '米山', id: 6, code: 666)
Member.create(name: '榎本', id: 7, code: 777)
